version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
      - RATE_LIMIT_PER_MINUTE=60
      - CACHE_TTL_HOURS=24
      - MAX_TEXT_LENGTH=5000
      - ENABLE_CORS=true
      - CORS_ORIGINS=["*"]
    volumes:
      - ./secrets:/secrets:ro
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - vibevoice-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - vibevoice-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - vibevoice-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  vibevoice-network:
    driver: bridge