version: '3.8'

services:
  api:
    build: ./backend
    container_name: vibevoice-api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-key.json
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080,http://localhost:8100
      - RATE_LIMIT_PER_MINUTE=60
      - CACHE_TTL_HOURS=24
      - MAX_TEXT_LENGTH=5000
    volumes:
      - ./secrets:/secrets:ro
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - vibevoice-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: vibevoice-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - vibevoice-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: vibevoice-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - api
    networks:
      - vibevoice-network

volumes:
  redis_data:
    driver: local

networks:
  vibevoice-network:
    driver: bridge